//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MSO_Demo.rc
//
#define IDOK2                           2
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_MSO_DEMO_DIALOG             102
#define IDS_SECU_EXPORT_SCORE           102
#define IDS_TT_PROGRESS_CTRL            103
#define IDS_TT_ASYNC_CMD_MSG            104
#define IDS_TT_ASYNC_ENROLL_MSG         105
#define IDS_TT_VIEWER                   106
#define IDS_TT_VIEWER_CHECKBOX          107
#define IDS_TT_MINI_VIEWERCHECKBOX      108
#define IDS_TT_BUTTON_IDENT_MATCH       109
#define IDS_TT_BUTTON_VERIF_MATCH       110
#define IDS_TT_BUTTON_REMOVE_USER       111
#define IDS_TT_BUTTON_REMOVE_ALL        112
#define IDS_TT_BUTTON_ADD_USER          113
#define IDS_TT_BUTTON_CREATE_BASE       114
#define IDS_TT_BUTTON_DESTROY_BASE      115
#define IDS_TT_BUTTON_START             116
#define IDS_TT_BUTTON_CLOSE             117
#define IDS_SECU_SIGNED_DOWNLOAD        118
#define IDS_SECU_TUNNELING              119
#define IDS_SECU_OFFERED_SECU           120
#define IDS_SECU_PK_ONLY_SIGNED         121
#define IDS_MSO_CONFIGURATION           122
#define IDS_TT_INFO_USE_RAW             123
#define IDR_MAINFRAME                   128
#define IDD_PPAGE_ENROLL                129
#define IDD_PPAGE_IDENTIFY              130
#define IDD_PPAGE_CODE                  131
#define IDD_PPAGE_VERIFY                132
#define IDD_MSO_DISPLAY_RESULT          135
#define IDB_BITMAP_LOGO_SAGEM           138
#define IDD_PPAGE_PROCESS               146
#define IDD_CONNECTION                  149
#define IDI_MSO                         150
#define IDD_REMOVE_USER_DLG             151
#define IDD_UPDATE_USER_DLG             151
#define IDI_GREEN_LIGHT                 154
#define IDI_RED_LIGHT                   155
#define IDB_BITMAP_LGREEN               156
#define IDB_BITMAP_LYELLOW              157
#define IDB_BITMAP_LRED                 158
#define IDB_BITMAP_LOGO_MORPHOSMART     160
#define IDD_PPAGE_GET_IMAGE             161
#define IDD_IMAGE                       162
#define IDD_PROGRESS_INIT               165
#define IDR_MENU_SECU                   167
#define IDD_MSO_CONF                    170
#define IDI_NOK                         171
#define IDI_NO                          172
#define IDI_OK                          173
#define IDI_YES                         174
#define IDD_CONNECTION_PSHEET_USB       178
#define IDD_CONNECTION_PSHEET_SERIAL    179
#define IDC_CURSOR1                     179
#define IDD_CONNECTION_PSHEET_PIPE      180
#define IDD_CONNECTION_PSHEET_SLAVEPIPE 180
#define IDD_BASE_OPTION                 183
#define IDD_PPAGE_MOC                   184
#define IDB_HAND_RIGHT                  184
#define IDB_HAND_LEFT                   185
#define IDD_TAB_DB_INFO                 185
#define IDD_TAB_BIO_SETTINGS            187
#define IDB_BITMAP1                     187
#define IDB_BITMAP_DROIT                187
#define IDD_TAB_OPTIONS                 188
#define IDB_BITMAP_LOGO_SAGEM_BLUE      191
#define IDB_BITMAP2                     192
#define IDB_BITMAP_LOGO_SAGEM_BLACK     192
#define IDD_MSO_ISO19794_FIR_INFO       194
#define IDB_BITMAP3                     196
#define IDB_BITMAP_OK                   196
#define IDB_BITMAP4                     197
#define IDB_BITMAP_KO                   197
#define IDB_UP_BMP                      198
#define IDB_RIGHT_BMP                   199
#define IDB_DOWN_BMP                    200
#define IDB_BITMAP6                     201
#define IDB_LEFT_BMP                    201
#define IDD_DIALOG_BIO_DATA_ENCRYPTION  202
#define IDD_DIALOG_GET_INFO             203
#define IDC_LIST_USER                   1000
#define IDC_BUTTON_START                1003
#define IDC_BUTTON2                     1006
#define IDC_BUTTON_CLOSE                1006
#define IDC_EDIT_TIMEOUT                1007
#define IDC_BUTTON_REMOVEALL            1008
#define IDC_BUTTON_REMOVE_ALL           1008
#define IDC_BUTTON_REMOVEUSER           1009
#define IDC_BUTTON_REMOVE_USER          1009
#define IDC_BUTTON5                     1010
#define IDC_BUTTON_ADD_USER             1010
#define IDC_PSHEET_AREA                 1011
#define IDC_EDIT_CODE_FIRSTNAME         1012
#define IDC_BUTTON_VERIF_MATCH          1012
#define IDC_IDC_EDIT_CODE_LASTNAME      1013
#define IDC_BUTTON_IDENT_MATCH          1013
#define IDC_RADIO_INPUTFILE             1014
#define IDC_BUTTON_UPDATE_USER          1014
#define IDC_RADIO_INPUTSMC              1015
#define IDC_RADIO_CAPTURE_ENROLL        1016
#define IDC_RADIO_CAPTURE_VERIF         1017
#define IDC_RADIO_INPUTSMC_INTERNAL     1017
#define IDC_EDIT_ENROLL_ID              1018
#define IDC_RADIO_CODE_ONEFINGER        1018
#define IDC_EDIT_ENROLL_FIRSTNAME       1019
#define IDC_RADIO_CODE_TWOFINGER        1019
#define IDC_EDIT_ENROLL_LASTNAME        1020
#define IDC_RADIO_ENROLL_ONEFINGER      1021
#define IDC_RADIO_ENROLL_TWOFINGERS     1022
#define IDC_EDIT_CODE_ID                1023
#define IDC_RADIO_CODE_TOKEN_BIO        1024
#define IDC_RADIO_CODE_OUTPUTFILE       1025
#define IDC_RADIO_CODE_OUTPUTSMC        1026
#define IDC_STATIC_IP                   1026
#define IDC_CURRENT_NB_RECORDS          1027
#define IDC_SERIAL_NAME                 1027
#define IDC_RADIO_CODE_OUTPUTSMC2       1027
#define IDC_RADIO_CODE_OUTPUTMOC        1027
#define IDC_NB_FINGERS                  1028
#define IDC_STATIC_MSG1                 1029
#define IDC_STATIC_SERIALNAME           1029
#define IDC_STATIC_MSG2                 1030
#define IDC_STATIC_MSG3                 1031
#define IDC_STATIC_MSG4                 1032
#define IDC_STATIC_ASYNC_MSG            1033
#define IDC_STATIC_ASYNC_CMD_MSG        1033
#define IDC_STATIC_MSG5                 1033
#define IDC_RADIO_CODE_OUTPUTFILE_PKC   1033
#define IDC_EDIT_THRESHOLD              1034
#define IDC_STATIC_MSG6                 1034
#define IDC_BUTTON_CREATE_BASE          1035
#define IDC_RADIO_CODE_OUTPUTFILE_PKCN  1035
#define IDC_BUTTON_DESTROY_BASE         1036
#define IDC_RADIO_CODE_OUTPUTFILE_PKM   1036
#define IDC_STATIC_ASYNC_CMD_MSG2       1037
#define IDC_RADIO_CODE_OUTPUTFILE_PKMN  1037
#define IDC_STATIC_QUALITY_MSG          1037
#define IDC_STATIC_QUALITY_MSG18        1037
#define IDC_BUTTON1                     1039
#define IDC_TEST_HOST                   1039
#define IDC_REBOOTSOFT                  1039
#define IDC_STATIC_ASYNC_ENROLL_MSG     1040
#define IDC_BITMAP_POSITION             1041
#define IDC_STATIC_MINI_VIEWER_1_1      1042
#define IDC_STATIC_MINI_VIEWER_1_2      1043
#define IDC_STATIC_MINI_VIEWER_1_3      1044
#define IDC_STATIC_MINI_VIEWER_2_1      1045
#define IDC_STATIC_MINI_VIEWER_2_2      1046
#define IDC_STATIC_MINI_VIEWER_2_3      1047
#define IDC_STATIC_VIEWER               1048
#define IDC_CHECK_MINI_VIEWER_ACTIVE    1049
#define IDC_CHECK_MAIN_VIEWER_ACTIVE    1050
#define IDC_PORT_COM                    1053
#define IDC_BAUD_RATE                   1054
#define IDC_STATIC_COM                  1055
#define IDC_STATIC_BAUD                 1056
#define IDC_RADIO_RS232                 1057
#define IDC_RADIO_USB                   1058
#define IDC_PRODUCT_DESC                1062
#define IDC_SENSOR_DESC                 1063
#define IDC_EDIT_ID                     1063
#define IDC_SOFTWARE_DESC               1064
#define IDC_PROGRESS_ADD_USER           1064
#define IDC_RADIO_LOCALBASE             1065
#define IDC_RADIO_MATCH_WITH_FILE       1066
#define IDC_RADIO_MATCH_WITH_SMC        1067
#define IDC_STATIC_BMP_BASE             1068
#define IDC_BITMAP_LOGO_SAGEM           1069
#define IDC_IMAGE                       1070
#define IDC_MAX_NB_RECORDS              1071
#define IDC_STATIC_MESS                 1074
#define IDC_STATIC_MESS2                1075
#define IDC_STATIC_MESS3                1076
#define IDC_STATIC_MESS4                1077
#define IDC_STATIC_MESS5                1078
#define IDC_STATIC_MESS10               1079
#define IDC_STATIC_MESS11               1080
#define IDC_STATIC_MESS12               1081
#define IDC_STATIC_MAINMESS             1082
#define IDC_STATIC_MESS13               1083
#define IDC_STATIC_MESS14               1084
#define IDC_STATIC_BIOAVI               1085
#define IDC_EDIT_SERIAL_NUMBER          1086
#define IDC_SERIAL_NUM_TXT              1087
#define IDC_EDIT_FAR                    1088
#define IDC_FAR_TXT                     1089
#define IDC_SECU_OPTIONS                1090
#define IDC_OPTIONS_TXT                 1091
#define IDC_LATENT_DETECT               1092
#define IDC_EDIT_FAR2                   1092
#define IDC_EDIT_MINMSL                 1092
#define IDC_CHECK_CODE_TOKEN_BIO        1093
#define IDC_MINMSL_TXT                  1093
#define IDC_RADIO_COMPRESS_V1           1094
#define IDC_CHECK_NO_CHECK              1095
#define IDC_FFD_SECU_LEVEL              1096
#define IDC_CHECK_EXPORT_NUM_PK         1097
#define IDC_OUTPUT_FILE_TYPE            1098
#define IDC_CODER_CHOICE                1098
#define IDC_RADIO_GET_IMAGE_VERIF_DETECT_MODE_CHOICE 1099
#define IDC_DIVERSIFICATION_TYPE        1099
#define IDC_RADIO_GET_IMAGE_ENROLL_DETECT_MODE_CHOICE 1100
#define IDC_WORKFLOW_TYPE               1100
#define IDC_BIO_MODE                    1100
#define IDC_CIPHERED_TYPE               1100
#define IDC_CHECK_WAKE_UP_MODE          1101
#define IDC_WORKFLOW_TYPE2              1101
#define IDC_PADDING_TYPE                1101
#define IDC_STRATEGY_MODE               1101
#define IDC_CHECK_ASYNC_COMMAND         1102
#define IDC_CHAIN_TYPE                  1102
#define IDC_CHECK_ENROLL_COMMAND        1103
#define IDC_RADIO_VERIF_ONEFINGER       1103
#define IDC_CHECK_ASYNC_DETECT_QUALITY  1104
#define IDC_RADIO_VERIF_TWOFINGERS      1104
#define IDC_CHECK_ASYNC_CODE_QUALITY    1105
#define IDC_GET_IMAGE_LATENT            1105
#define IDC_PPAGE                       1106
#define IDC_ADDRESS_NAME                1107
#define IDC_IP_FORMAT                   1108
#define IDC_IP_FORMAT2                  1109
#define IDC_IMAGE_INFO                  1110
#define IDC_COMBO1                      1113
#define IDC_CARD_TYPE                   1113
#define IDC_OUTPUT_FVP_FILE_TYPE        1113
#define IDC_CONFIG_DEFAULT_BAUD_RATE    1113
#define IDC_CMB_ENCRYPT                 1113
#define IDC_RADIO1                      1114
#define IDC_RADIO_MOC_ENROLL            1114
#define IDC_RADIO_MOC_ACTION_TYPE       1114
#define IDC_RADIO_NO                    1114
#define IDC_COMPRESSION_TYPE            1115
#define IDC_RADIO_MOC_VERIF             1115
#define IDC_COMBO2                      1116
#define IDC_RADIO_CARD_TYPE_V2          1116
#define IDC_CONFIG_SLEEP_TIMEOUT        1116
#define IDC_FINGER_INDEX                1116
#define IDC_LIST1                       1117
#define IDC_COMPRESSION_RATE            1121
#define IDC_TEXT_COMPRESSION_RATE       1122
#define IDC_MAX_BASE                    1128
#define IDC_MAX_RECORD                  1128
#define IDC_NUM_FINGER                  1129
#define IDC_NUM_FIELD                   1130
#define IDC_APDU_TO_SEND                1132
#define IDC_FINGERPRINT_LEFT_LITTLE     1141
#define IDC_FINGERPRINT_LEFT_RING       1142
#define IDC_FINGERPRINT_LEFT_MIDDLE     1143
#define IDC_FINGERPRINT_LEFT_INDEX      1144
#define IDC_FINGERPRINT_LEFT_THUMB      1145
#define IDC_HAND_LEFT                   1146
#define IDC_HAND_RIGHT                  1147
#define IDC_FINGERPRINT_RIGHT_LITTLE    1148
#define IDC_RADIO_CARD_TYPE_V1          1149
#define IDC_RADIO3                      1150
#define IDC_FINGERPRINT_RIGHT_RING      1151
#define IDC_FINGERPRINT_RIGHT_MIDDLE    1152
#define IDC_FINGERPRINT_RIGHT_INDEX     1153
#define IDC_FINGERPRINT_LEFT_THUMB2     1154
#define IDC_FINGERPRINT_RIGHT_THUMB     1154
#define IDC_STATIC_CHOOSE_FINGER        1156
#define IDC_CHECK1                      1157
#define IDC_RADIO_CARD_S2_DIVERSIFICATION 1157
#define IDC_SAVE_IN_BD_CHECK            1157
#define IDC_CHECK_FFPLACEMENT_ON_TOP    1157
#define IDC_STATIC_TEMPLATE_TYPE        1158
#define IDC_TEMPLATE_TYPE               1158
#define IDC_D0                          1159
#define IDC_TAB1                        1160
#define IDC_TABCTRL                     1160
#define IDC_D1                          1161
#define IDC_STATIC_ANIMATION_PIC        1161
#define IDC_D2                          1162
#define IDC_QPROGRESS1                  1162
#define IDC_QUALITE_PROGRESS            1162
#define IDC_D3                          1163
#define IDC_DIRECTION_PIC               1163
#define IDC_STATIC_ASYNC_ENROLL_DIRECTION_PIC 1164
#define IDC_COMBO3                      1165
#define IDC_CONFIG_SENSOR_WIN_POSITION  1165
#define IDC_STATIC_FVP                  1166
#define IDC_SYNC_QUALITY                1168
#define IDC_EDIT_RESX                   1169
#define IDC_EDIT_RESY                   1170
#define IDC_EDIT_NBROWS                 1171
#define IDC_EDIT_NBCOLS                 1172
#define IDC_EDIT5                       1173
#define IDC_EDIT_NB_BIT_PPIXEL          1173
#define IDC_CHECK_ASLC                  1175
#define IDC_CHECK_FINGERPRINT_QUALITY   1176
#define IDC_EDIT_FINGERPRINT_QUALITY    1177
#define IDC_EDIT                        1177
#define IDC_EDIT_DIVERSIFICATION_DATA   1177
#define IDC_CHECK2                      1178
#define IDC_CHECK_UPDATE_FINGER         1178
#define IDC_ENCRYP_DB                   1181
#define IDC_ENCRY_DB                    1181
#define IDC_VAL_ECRYP_DB                1182
#define IDC_RADIO2                      1183
#define IDC_RADIO_YES                   1183
#define IDC_GET_INFO                    1183
#define IDC_STATIC_ADD_UPDATE           1184
#define IDC_MAX_SIZE                    1185
#define IDC_TEMPLATE_MAX_SIZE           1185
#define IDC_STATIC_MAX_SIZE             1186
#define IDC_FULL_CCID                   1187
#define IDC_STATIC_T_TYPE               1188
#define IDC_EDIT_MSG                    1189
#define IDC_APDU_MAX_LENGTH             1190
#define IDC_STATIC_MAX_LENGTH           1191
#define IDC_IPADDRESS                   3002
#define IDC_IPPORT                      3004
#define IDC_STATIC_IPPORT               3005
#define ID_READ_CONFIGURATION           32771
#define ID_LOAD_PKCS12                  32772
#define ID_STORE_CERTIFICAT             32773
#define ID_READ_CERTIFICAT              32774
#define ID_VERIF_SIGN_X984              32778
#define ID_EXTRACT_SIGNER_ID            32779
#define ID_LOAD_MASTER_KEY              32780
#define ID_UNCOMPRESS_IMAGE             32783
#define ID_LOAD_MOC_KENC                32784
#define ID_SECURITY_DISPLAYMOCKENCKCV   32785
#define ID_DISPLAY_MOC_KENC_KCV         32786
#define ID_SECURITY_DISPLAYLOCKKEYKCV   32787
#define ID_Menu                         32789
#define ID_TOOLS_FVPMMIFILE             32790
#define ID_FVPMMIFILE_SAVEAS            32791
#define ID_FVP_MMI_FILE_LOAD            32792
#define ID_FVP_MMI_FILE_SAVEAS          32793
#define ID_FVP_MMI_FILE_RESET           32794
#define ID_TOOLS_CONVERTTOISO           32795
#define ID_CONVERT_ISO19794_FIR         32796
#define IDC_STATIC_GRPBOX_COMPRESS      32797
#define ID_SECURITY_GET_KS_KCV          32797
#define IDC_STATIC_GRPBOX_INFO          32798
#define ID_SECURITY_LOAD_KS             32798
#define IDC_COMBO_DESIRED_COMPRESS      32799
#define ID_SECURITY_GETKSKCV            32799
#define ID_SECURITY_DISPLAY_KS_KCV      32800
#define ID_SECURITY_ENABLE_BIO_DATA_ENCRYPTION 32801
#define ID_SECURITY_LOAD_KS_SYMMSEC     32802
#define ID_SECURITY_LOAD_KS_ASYMMSEC    32803
#define IDC_CHECK_CONFIG_KEYUSER        32804
#define ID_SECURITY_DECRYPT_BIOMETRIC_DATA 32805
#define ID_SECURITY_ENCRYPT_AES_DATA    32806
#define ID_SECURITY_DECRYPT_AES_DATA    32807
#define ID_SECURITY_PRIVACY_MODE        32808
#define ID_SECURITY_LOAD_KPRIVACY			32809
#define ID_SECURITY_LOAD_KPRIVACY_SYMMSEC   32810
#define ID_SECURITY_PRIVACY_MODE_Enable_NoOperationDB				32811
#define ID_SECURITY_PRIVACY_MODE_Enable_EraseDB						32812
#define ID_SECURITY_PRIVACY_MODE_Enable_CipherDB					32813
#define ID_SECURITY_PRIVACY_MODE_Disable_NoOperationDB				32814
#define ID_SECURITY_PRIVACY_MODE_Disable_EraseDB					32815
#define ID_SECURITY_PRIVACY_MODE_Disable_CipherDB					32816
#define ID_SECURITY_PRIVACY_MODE_Standalone_NoOperationDB			32817
#define ID_SECURITY_PRIVACY_MODE_Standalone_EraseDB					32818
#define ID_SECURITY_PRIVACY_MODE_Standalone_CipherDB				32819
#define ID_SECURITY_PRIVACY_MODE_PartialEnable_NoOperationDB        32820
#define ID_SECURITY_PRIVACY_MODE_PartialEnable_EraseDB				32821
#define ID_SECURITY_PRIVACY_MODE_PartialEnable_CipherDB				32822
#define ID_SECURITY_DISPLAY_KPRIVACY_KCV							32823

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        204
#define _APS_NEXT_COMMAND_VALUE         32809
#define _APS_NEXT_CONTROL_VALUE         1192
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
