/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package morpho.msosecu.sdk.api;

public class MsoSecuJNI {
  public final static native int TRIPLE_DES_KEY_LENGTH_get();
  public final static native int DES_BLOCK_LENGTH_get();
  public final static native int AES128_BLOCK_LENGTH_get();
  public final static native int getHostCertif(java.util.ArrayList<Byte> jarg1);
  public final static native int genRandom(byte[] jarg1);
  public final static native int tunnelingInit1(byte[] jarg1, byte[] jarg3, byte[] jarg5, byte[] jarg7, java.util.ArrayList<Byte> jarg9);
  public final static native int tunnelingInit2(byte[] jarg1);
  public final static native int tripleDesSign(byte[] jarg1, java.util.ArrayList<Byte> jarg3);
  public final static native int tripleDesCrypt(byte[] jarg1, java.util.ArrayList<Byte> jarg3);
  public final static native int desCrypt(byte[] jarg1, byte[] jarg2, java.util.ArrayList<Byte> jarg4);
  public final static native int tripleDesVerifSign(byte[] jarg1, byte[] jarg3, boolean[] jarg4);
  public final static native int tripleDesDecrypt(byte[] jarg1, java.util.ArrayList<Byte> jarg3);
  public final static native int verifOfferedSecuritySignature(byte[] jarg1, byte[] jarg3, byte[] jarg5, int[] jarg7);
  public final static native int verifSignRSA(byte[] jarg1, byte[] jarg3, byte[] jarg5, int[] jarg7);
  public final static native int verifSignDSA(byte[] jarg1, byte[] jarg3, byte[] jarg5, int[] jarg7);
  public final static native int verifCertif(byte[] jarg1, int[] jarg3);
  public final static native int tripleDesCryptByKey(byte[] jarg1, byte[] jarg2, java.util.ArrayList<Byte> jarg4);
  public final static native int rsaEncrypt(byte[] jarg1, byte[] jarg3, java.util.ArrayList<Byte> jarg5);
  public final static native int signRSA(byte[] jarg1, byte[] jarg3, java.util.ArrayList<Byte> jarg5);
  public final static native int encrypt3DesCbcNopad(byte[] jarg1, byte[] jarg2, int jarg3, byte[] jarg4, byte[] jarg5);
  public final static native int setOpenSSLPath(String jarg1);
  public final static native int encryptAes128Cbc(byte[] jarg1, byte[] jarg3, byte[] jarg5, boolean jarg6, java.util.ArrayList<Byte> jarg7);
  public final static native int decryptAes128Cbc(byte[] jarg1, byte[] jarg3, byte[] jarg5, boolean jarg6, java.util.ArrayList<Byte> jarg7);
  public final static native int computeCRC32(byte[] jarg1, long jarg3, long jarg4, boolean jarg5, boolean jarg6, long jarg7, long[] jarg8);
  public final static native int MSOSECU_OK_get();
  public final static native int MSOSECU_BAD_PARAMETER_get();
  public final static native int MSOSECU_OPEN_FILE_ERR_get();
  public final static native int MSOSECU_WRITE_FILE_ERR_get();
  public final static native int MSOSECU_READ_FILE_ERR_get();
  public final static native int MSOSECU_DELETE_FILE_ERR_get();
  public final static native int MSOSECU_FILE_EMPTY_get();
  public final static native int MSOSECU_FILE_ERR_get();
  public final static native int MSOSECU_ALLOC_ERR_get();
  public final static native int MSOSECU_CRYPTO_PROTOCOLE_ERR_get();
  public final static native int MSOSECU_OPEN_SSL_get();
  public final static native int MSOSECU_INVALID_CERTIF_get();
  public final static native int MSOSECU_PARSE_DER_TO_X509STRUCT_ERR_get();
  public final static native int MSOSECU_STORE_NEW_ERR_get();
  public final static native int MSOSECU_STORE_LOAD_LOCATIONS_ERR_get();
  public final static native int MSOSECU_PEM_READ_BIO_ERR_get();
  public final static native int MSOSECU_MODE_DSA_ERR_get();
  public final static native int MSOSECU_SHA1_INIT_ERR_get();
  public final static native int MSOSECU_SHA1_UPDATE_ERR_get();
  public final static native int MSOSECU_SHA1_FINAL_ERR_get();
  public final static native int MSOSECU_DSS1_INIT_ERR_get();
  public final static native int MSOSECU_DSS1_UPDATE_ERR_get();
  public final static native int MSOSECU_DSS1_FINAL_ERR_get();
  public final static native int MSOSECU_BIO_NEW_MEM_ERR_get();
  public final static native int MSOSECU_PARSE_DATA_TO_X509STRUCT_ERR_get();
  public final static native int MSOSECU_PUBLIC_KEY_ERR_get();
  public final static native int MSOSECU_RSA_KEY_ERR_get();
  public final static native int MSOSECU_DSA_KEY_ERR_get();
  public final static native int MSOSECU_AES128_INIT_ERR_get();
  public final static native int MSOSECU_AES128_UPDATE_ERR_get();
  public final static native int MSOSECU_AES128_FINAL_ERR_get();
}
